### ISSUE TITLE
Time is too big on linux

### ISSUE THREAD

**Issue by ticoombs** [badanka/Compact#29]
![screenshot from 2017-03-11 21-50-01](https://cloud.githubusercontent.com/assets/2687896/23822642/02fa4f9c-06a5-11e7-82ae-6f199663afb1.png)

On screen overlay under Linux the time seems to be too big.

Yes I have enabled the linux settings, and yes I've installed the font.

**Comment by badanka** [comment]
Oops. Time to get a new Linux VM going. It'll be improved in the next update.

**Comment by badanka** [comment]
Alright, apparently Steam no longer reads certain values from _linux.styles_ anymore. I've moved the code into the "usual" place for now. So if you want a quick fix you can download the current master at https://github.com/badanka/Compact/archive/master.zip for now.
![20170315213446_1](https://cloud.githubusercontent.com/assets/627377/23970065/ec2284c0-09c8-11e7-9b8b-e606f577294a.jpg)

I'll have to go through the entire _linux.styles_ file and see if anything else has stopped working lately. But I'm going to need to set up a new VM instead of using my almost ten year old laptop (with a barely functioning wifi and a dead battery) to properly check this. I aim to have this done until the next release, but I can't say when that'll be unfortunately. I hope this works for you until then.

**Comment by ticoombs** [comment]
Using latest master fixed it. 
Technically It's not as flush as yours but i just want to know what time it is. Feel free to close. 
![screenshot from 2017-03-21 20-30-58](https://cloud.githubusercontent.com/assets/2687896/24140780/543d4a44-0e75-11e7-89ca-1812bd36d67a.png)

**Comment by badanka** [comment]
Yeah, I updated the master build once more fter I posted that comment. I need to do some more adjustments, but I couldn't get Ubuntu to show 12-hour time with AM/PM in the overlay. So I'll have to do that separately. together with some other Linux related fixes. When I've done that I'll update and close this issue.

**Comment by badanka** [comment]
This should now be fixed with the release of 1.5.92.
