### ISSUE TITLE
Style is broken on new Steam Beta update

### ISSUE THREAD

**Issue by ssolidus** [badanka/Compact#37]
Please see this screenshot:
![image](https://user-images.githubusercontent.com/14216632/41341575-67107702-6f3d-11e8-855a-42b2394b123b.png)

**Comment by badanka** [comment]
I'm aware. I don't have a version that's compatible with the Steam beta. If you're going to help Steam with testing their beta version I'd recommend using the default skin, which is also what they recommend. I am however keeping track of the changes for the day when they push it to stable.

**Comment by ssolidus** [comment]
I know that you don't officially support the Steam beta, but wouldn't it make sense to begin making the necessary changes now, so that you can release it earlier?

**Comment by badanka** [comment]
It does, and I do. But I've been burned so many times where they've released a second beta where everything is changed yet again, forcing me to start from scratch. This has over the years led to even more frustration both for me and users. And since it's so difficult to get it across to people that beta development can and will be less smooth than using stable versions I stopped releasing my own beta versions that I have at home to the public. But I always subscribe to all beta releases and compare the changes to stay on track as much as my schedule allows. 

And if it's very minor things I might push some changes to the master branch without publishing a release. As soon as I promise more than that the floodgates of angry posts and erroneous bug reports open. I wish it wouldn't, but...

**Comment by HairyMilkshakes** [comment]
Gonna just wait patiently!
