### ISSUE TITLE
Direct-play steam update

### ISSUE THREAD

**Issue by avsaponchik** [badanka/Compact#45]
New buttons were added to:
  Settings - Remote Play tab
![изображение](https://user-images.githubusercontent.com/1337953/57835312-e9b9ab00-77c6-11e9-87e4-347f458bbb30.png)

  Settings - Interface tab
![изображение](https://user-images.githubusercontent.com/1337953/57835277-d575ae00-77c6-11e9-887e-321f8cee12ae.png)

  Settings - Controller tab
![изображение](https://user-images.githubusercontent.com/1337953/57835255-cf7fcd00-77c6-11e9-922b-5a3d92072f3e.png)

Also minor thing i noticed is that 'Report bug' 'hitbox' is misaligned
https://i.imgur.com/R1A1Eyx.gif

**Comment by badanka** [comment]
I don't keep up with the beta updates, but I'm keeping an eye on updates and preparing changes for the next stable version. There's also another new element for the Steam Controller notification that I unfortunately haven't added yet.

I wasn't aware of the 'Report bug' button though, I'll have to check that as soon as I get the chance. Thanks!

**Comment by badanka** [comment]
The 'Report bug' has apparently been missing for a while in earlier versions. This issue popped up now with the beta. As previously said I don't really keep up with betas but I'll start pushing some changes in preparation to the master branch when I have the time and energy. The things you've noticed in this issue have been taken care of if you use the master branch instead of the latest release. Use at your own risk though.
